apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-mongo-pv
  labels:
    name: auth-mongo-pv
spec:
  storageClassName: auth-sc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mgmt/data/auth-mongo"