apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
  labels:
    name: auth-mongo-pvc
spec:
  storageClassName: auth-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi