apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: follow-mongo-pvc
  labels:
    name: follow-mongo-pvc
spec:
  storageClassName: follow-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi