apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    name: minio-pvc
spec:
  storageClassName: minio-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi