apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    name: minio-pv
spec:
  storageClassName: minio-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mgmt/data/minio"