apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-mongo-pv
  labels:
    name: user-mongo-pv
spec:
  storageClassName: user-sc
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mgmt/data/user-mongo"