apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-mongo
  template:
    metadata:
      labels:
        app: user-mongo
    spec:
      containers:
        - name: user-mongo
          image: mongo
          volumeMounts:
            - name: user-mongo-volume
              mountPath: /data/db
      volumes:
        - name: user-mongo-volume
          persistentVolumeClaim:
            claimName: user-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongo-svc
spec:
  selector:
    app: user-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
